// location
const LOCATION_GLOBAL = 0
const LOCATION_USA = 1
const LOCATION_ONSITE = 2

// access level
const ACCESS_RESTRICTED = 0
const ACCESS_ONLOCATION = 1
const ACCESS_ONLINE = 2

const AccessTypes = {
  LOCATION_GLOBAL: LOCATION_GLOBAL,
  LOCATION_USA: LOCATION_USA,
  LOCATION_ONSITE: LOCATION_ONSITE,
  ACCESS_RESTRICTED: ACCESS_RESTRICTED,
  ACCESS_ONLOCATION: ACCESS_ONLOCATION,
  ACCESS_ONLINE: ACCESS_ONLINE,
}

export { AccessTypes }
