// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/organizations/:orgId": {
    params: {
      "orgId": string;
    };
  };
  "/organizations": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/search/:guid": {
    params: {
      "guid": string;
    };
  };
  "/collections": {
    params: {};
  };
  "/contribute": {
    params: {};
  };
  "/our-story": {
    params: {};
  };
  "/subscribe": {
    params: {};
  };
  "/about": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/organizations/:orgId" | "/organizations" | "/search" | "/search/:guid" | "/collections" | "/contribute" | "/our-story" | "/subscribe" | "/about";
  };
  "routes/organizations.$orgId.jsx": {
    id: "routes/organizations.$orgId";
    page: "/organizations/:orgId";
  };
  "routes/organizations._index.jsx": {
    id: "routes/organizations._index";
    page: "/organizations";
  };
  "routes/search._index.jsx": {
    id: "routes/search._index";
    page: "/search";
  };
  "routes/search.$guid.jsx": {
    id: "routes/search.$guid";
    page: "/search/:guid";
  };
  "routes/collections.jsx": {
    id: "routes/collections";
    page: "/collections";
  };
  "routes/contribute.jsx": {
    id: "routes/contribute";
    page: "/contribute";
  };
  "routes/our-story.jsx": {
    id: "routes/our-story";
    page: "/our-story";
  };
  "routes/subscribe.jsx": {
    id: "routes/subscribe";
    page: "/subscribe";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/about.jsx": {
    id: "routes/about";
    page: "/about";
  };
};